#!/usr/bin/python3
# Qwen Code: local token usage from ~/.qwen/{tmp,projects}/*/chats.
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))
from _agentusage import HOME, Usage, cached_scan, emit, max_age, parse_args
import _gemini_chats

ROOTS = [HOME / ".qwen" / "tmp", HOME / ".qwen" / "projects"]


def scan():
  usage = Usage()
  complete = _gemini_chats.scan(usage, ROOTS, "qwen")
  return usage.stats(), complete


args = parse_args()
emit("qwen", "Qwen Code", cached_scan("qwen", scan, max_age(args), str(ROOTS)))
